version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      routine-updates:
        update-types:
          - minor
          - patch
        patterns:
          - "*"
    open-pull-requests-limit: 5
